
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialize: true
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
    show-sql: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webui/

security:
  ignored:
  - "*.bundle.*"
server:
  context-path: /